#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef struct motorSpeeds {
	int a;
	bool _a;
	int b;
	bool _b;
	int c;
	bool _c;
	int d;
	bool _d;
} t_motorSpeeds;

t_motorSpeeds setSpeeds;
t_motorSpeeds cSpeeds;


task moveMotors() {
	for(;;) {
		// Motor A
		if(abs(setSpeeds.a - cSpeeds.a) > 1) {
			//Different speed, update.
			motor[motorA] = setSpeeds.a;
			cSpeeds.a = setSpeeds.a;
			} else {
			// Not update to speed, +- 1 from speed.
			if(setSpeeds._a) {
				// Add 1 to get back to normal speed
				motor[motorA] = cSpeeds.a;
				setSpeeds._a = !setSpeeds._a;
				} else {
				motor[motorA] = cSpeeds.a - 1;
				setSpeeds._a = !setSpeeds._a;
			}
		}
		//Motor B
		if(abs(setSpeeds.b - cSpeeds.b) > 1) {
			//Different speed, update.
			motor[motorB] = setSpeeds.b;
			cSpeeds.b = setSpeeds.b;
			} else {
			// Not update to speed, +- 1 from speed.
			if(setSpeeds._b) {
				// Add 1 to get back to normal speed
				motor[motorB] = cSpeeds.b;
				setSpeeds._b = !setSpeeds._b;
				} else {
				motor[motorB] = cSpeeds.b - 1;
				setSpeeds._b = !setSpeeds._b;
			}
		}
		// Motor C
		if(abs(setSpeeds.c - cSpeeds.c) > 1) {
			//Different speed, update.
			motor[motorC] = setSpeeds.c;
			cSpeeds.c = setSpeeds.c;
			} else {
			// Not update to speed, +- 1 from speed.
			if(setSpeeds._c) {
				// Add 1 to get back to normal speed
				motor[motorC] = cSpeeds.c;
				setSpeeds._c = !setSpeeds._c;
				} else {
				motor[motorC] = cSpeeds.c - 1;
				setSpeeds._c = !setSpeeds._c;
			}
		}
		// Motor D
		if(abs(setSpeeds.d - cSpeeds.d) > 1) {
			//Different speed, update.
			motor[motorD] = setSpeeds.d;
			cSpeeds.d = setSpeeds.d;
			} else {
			// Not update to speed, +- 1 from speed.
			if(setSpeeds._d) {
				// Add 1 to get back to normal speed
				motor[motorD] = cSpeeds.d;
				setSpeeds._d = !setSpeeds._d;
				} else {
				motor[motorD] = cSpeeds.d - 1;
				setSpeeds._d = !setSpeeds._d;
			}
		}
	}
}

task main()
{
	startTask(moveMotors);
	for(;;) {
		for(int i = 0; i < 100; i++) {
			setSpeeds.d = i;
			setSpeeds.c = i;
			delay(100);
		}
	}


}
